// generated by scripts/gen-stories.ts — 손으로 고치면 다음 생성 때 건너뜀
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Textarea } from './Textarea';

const meta: Meta<typeof Textarea> = {
  title: 'Components/Textarea',
  component: Textarea,
  tags: ['autodocs'],
  args: {
    label: '라벨',
    helper: '도움말',
  },
  argTypes: {
    label: { control: false },
    helper: { control: false },
    autoGrow: { control: 'boolean' },
    fieldProps: { control: false },
  },
  parameters: { docs: { description: { component: `여러 줄 입력 + 글자수.

**Requirements**
- maxLength 카운터, 90% 경고색, autoGrow
- 한 글자 입력 → 카운터 갱신 ≤ 1 프레임
- autoGrow 시 CLS: 높이 변화는 사용자 입력에 의한 것이라 CLS 집계 제외 — 그래도 max-height 로 상한` } } },
};
export default meta;
type S = StoryObj<typeof Textarea>;
export const Default: S = {};

