// theme.json 검증 + tokens.ts 생성.
//
// theme.json 은 **base 값의 SSOT** 입니다 — 테마별 bg · surface · text · accent · divider,
// 폰트, 반경, 간격, 모션, 이징. 배포되는 CSS(styles.css · theme-malt.css)가 이 값과
// 어긋나면 여기서 실패합니다.
//
// 램프(neutral-100..900 · accent-100..900)는 생성하지 않습니다. 배포 팔레트의 램프는
// 손으로 튜닝한 값이고 docs/contrast-audit.md 의 실측 대비값과 스토리북 axe 통과가
// 그 값에 걸려 있습니다. 알고리즘으로 다시 뽑으면 테마당 18개 값이 달라지고
// 검수 결과가 통째로 무효가 됩니다. 램프를 바꾸려면 CSS 를 고치고 대비 검수를
// 다시 하세요 — 그게 이 파일이 램프를 만들지 않는 이유입니다.
import { writeFileSync } from 'node:fs';
import themeJson from '../theme.json';
import { parseThemeFile } from './theme.schema';
import { compare, readVars, type Mismatch } from './verify-tokens';

const theme = parseThemeFile(themeJson);

const styles = readVars('../styles.css');
const malt = readVars('../theme-malt.css');

/** 테마 블록 → 그 값이 실제로 실려 나가는 셀렉터 */
const WHERE = {
  light: { file: 'styles.css', vars: styles[':root'] },
  dark: { file: 'styles.css', vars: styles['[data-theme=dark]'] },
  malt: { file: 'theme-malt.css', vars: malt['[data-theme=malt]'] },
} as const;

const problems: Mismatch[] = [];

for (const [name, block] of Object.entries(theme.themes)) {
  const target = WHERE[name as keyof typeof WHERE];
  const expected: Record<string, string | number> = {
    'color-bg': block.bg,
    'color-surface': block.surface,
    'color-text': block.text,
    'color-accent': block.accent,
  };
  if (block.divider) expected['color-divider'] = block.divider;
  if (block.fonts) {
    expected['font-heading'] = block.fonts.heading;
    expected['font-heading-weight'] = block.fonts.headingWeight;
    expected['font-body'] = block.fonts.body;
    if (block.fonts.mono) expected['font-mono'] = block.fonts.mono;
  }
  problems.push(...compare(`${target.file} [${name}]`, expected, target.vars));
}

// 루트 스칼라 — 폰트 · 간격 · 반경 · 모션 · 이징
const root: Record<string, string | number> = {
  'font-heading': theme.fonts.heading,
  'font-heading-weight': theme.fonts.headingWeight,
  'font-body': theme.fonts.body,
  'radius-sm': `${theme.radius}px`,
  'radius-md': `${theme.radius}px`,
  'radius-lg': `${theme.radius}px`,
};
theme.space.forEach((px, i) => (root[`space-${[1, 2, 3, 4, 6, 8][i]}`] = `${px}px`));
for (const [k, v] of Object.entries(theme.motion)) root[`motion-${k}`] = `${v}ms`;
for (const [k, v] of Object.entries(theme.easing)) root[`ease-${k}`] = v;
problems.push(...compare('styles.css [:root]', root, styles[':root']));

if (problems.length) {
  const lines = problems.map(p =>
    `  ${p.where} --${p.key}\n    theme.json: ${p.expected}\n    CSS:        ${p.actual ?? '(없음)'}`,
  );
  console.error(
    `theme.json 과 배포 CSS 가 어긋납니다 (${problems.length}건):\n${lines.join('\n')}\n\n` +
      'theme.json 이 base 값의 SSOT 입니다. CSS 를 theme.json 에 맞추거나,\n' +
      '값을 바꾸려는 것이라면 두 곳을 같이 고치고 docs/contrast-audit.md 를 다시 실측하세요.',
  );
  process.exit(1);
}

// RN/JS 소비용. CSS 를 못 쓰는 표면(React Native · 캔버스 · 이메일)이 같은 값을 씁니다.
const ts =
  `// generated by src/build-tokens.ts — 편집하지 말고 theme.json 을 고치세요\n` +
  `export const themes = ${JSON.stringify(theme.themes, null, 2)} as const;\n` +
  `export const motion = ${JSON.stringify(theme.motion)} as const;\n` +
  `export const space = ${JSON.stringify(theme.space)} as const;\n` +
  `export const easing = ${JSON.stringify(theme.easing)} as const;\n`;
writeFileSync(new URL('../tokens.ts', import.meta.url), ts);

console.log(`tokens: theme.json ↔ CSS ${Object.keys(theme.themes).length} 테마 일치, tokens.ts 생성`);
