// theme.json → styles.css(:root + [data-theme]) + tokens.ts. SSOT 는 theme.json 하나.
// 램프는 OKLCH 로 생성: 같은 hue/chroma, 명도만 9단계 — Modernist readme 의 "shared perceptual lightness scale".
import { writeFileSync } from 'node:fs';
import { converter, formatHex, parse } from 'culori';
import themeJson from '../theme.json';
import { parseThemeFile, type ThemeBlock } from './theme.schema';

// 스키마 검증을 먼저 통과해야 아래 생성 로직이 돈다 — 오타는 CSS 가 아니라 여기서 잡는다.
const theme = parseThemeFile(themeJson);

const toOklch = converter('oklch'), toRgb = converter('rgb');
const L = [0.97, 0.93, 0.86, 0.75, 0.62, 0.5, 0.4, 0.3, 0.22];       // 100..900 (light 기준)
const ramp = (hex: string, invert = false) => {
  const c = toOklch(parse(hex)!); const steps = (invert ? [...L].reverse() : L);
  return steps.map(l => formatHex(toRgb({ ...c, l, c: Math.min(c.c ?? 0, l > 0.9 ? 0.04 : l < 0.3 ? 0.12 : c.c ?? 0) })));
};
const vars = (o: Record<string, string | number>) => Object.entries(o).map(([k, v]) => `  --${k}: ${v};`).join('\n');

function block(name: string, t: ThemeBlock, dark = false) {
  const neutral = ramp(t.text, dark), accent = ramp(t.accent, dark);
  const o: Record<string, string | number> = {
    'color-bg': t.bg, 'color-surface': t.surface, 'color-text': t.text, 'color-accent': t.accent,
    'color-divider': t.divider ?? `color-mix(in srgb, ${t.text} ${Math.round((t.dividerAlpha ?? .4) * 100)}%, transparent)`,
  };
  neutral.forEach((h, i) => o[`color-neutral-${(i + 1) * 100}`] = h);
  accent.forEach((h, i) => o[`color-accent-${(i + 1) * 100}`] = h);
  if (t.fonts) { o['font-heading'] = t.fonts.heading; o['font-heading-weight'] = t.fonts.headingWeight; o['font-body'] = t.fonts.body; if (t.fonts.mono) o['font-mono'] = t.fonts.mono; }
  if (t.radius !== undefined) { o['radius-sm'] = o['radius-md'] = o['radius-lg'] = `${t.radius}px`; }
  Object.assign(o, t.extra ?? {});
  return (name === 'light' ? ':root' : `[data-theme=${name}]`) + ' {\n' + vars(o) + '\n}';
}

const root: Record<string, string | number> = { 'font-heading': theme.fonts.heading, 'font-heading-weight': theme.fonts.headingWeight, 'font-body': theme.fonts.body };
theme.space.forEach((px, i) => root[`space-${[1, 2, 3, 4, 6, 8][i]}`] = `${px}px`);
['sm', 'md', 'lg'].forEach(k => root[`radius-${k}`] = `${theme.radius}px`);
Object.entries(theme.motion).forEach(([k, v]) => root[`motion-${k}`] = `${v}ms`);
Object.entries(theme.easing).forEach(([k, v]) => root[`ease-${k}`] = v);

const css = [
  '/* generated by build-tokens.ts — 편집은 theme.json 에서 */',
  ':root {\n' + vars(root) + '\n}',
  block('light', theme.themes.light),
  block('dark', theme.themes.dark, true),
  block('malt', theme.themes.malt),
].join('\n\n');
writeFileSync(new URL('../generated.css', import.meta.url), css);

// tokens.ts — RN/JS 소비용 (bottling tokens.ts 와 같은 형태)
const ts = `// generated — see theme.json\nexport const themes = ${JSON.stringify(theme.themes, null, 2)} as const;\nexport const motion = ${JSON.stringify(theme.motion)} as const;\nexport const space = ${JSON.stringify(theme.space)} as const;\n`;
writeFileSync(new URL('../tokens.ts', import.meta.url), ts);
console.log('tokens: generated.css, tokens.ts');

// figma-tokens.json (Tokens Studio) 도 같은 소스에서 — 램프는 Figma 에선 생성하지 않고 base 색만 보낸다 (Figma 플러그인이 램프를 만들지 않으므로 필요 시 generated.css 의 값을 복사)
