// generated by scripts/gen-stories.ts — 손으로 고치면 다음 생성 때 건너뜀
import type { Meta, StoryObj } from '@storybook/react-vite';
import { DatePicker } from './DatePicker';

const meta: Meta<typeof DatePicker> = {
  title: 'Components/DatePicker',
  component: DatePicker,
  tags: ['autodocs'],
  args: {
    label: '라벨',
    placeholder: '입력하세요',
  },
  argTypes: {
    label: { control: false },
    withTime: { control: 'boolean' },
    time: { control: 'text' },
    onTimeChange: { control: false },
    min: { control: false },
    max: { control: false },
    placeholder: { control: 'text' },
    fieldProps: { control: false },
  },
  parameters: { docs: { description: { component: `Radix Popover + react-day-picker. 날짜(또는 기간) + 선택적 시간.

**Requirements**
- single / range, min·max, 로케일 ko, 시간은 네이티브 <input type=time>
- 열림 INP p75 ≤ 150ms (달력 42셀 렌더), 팝오버는 절대 위치 → CLS 0
- 키보드: 그리드 ←→↑↓ PgUp/PgDn Home End Enter, Esc 닫기 + 포커스 복귀
- 값은 Date 객체 — 표시 포맷은 @malt/domain formatDate 가, 상대 시각은 relativeTime 이` } } },
};
export default meta;
type S = StoryObj<typeof DatePicker>;
export const Default: S = {};

