/**
 * docs/radio/<Name>.md + <Name>.tsx 의 props 타입 → <Name>.stories.tsx 생성.
 *  - argTypes: props 타입의 유니언 리터럴 → inline-radio, boolean → boolean, string → text, 함수/ReactNode → control:false
 *  - docs.description.component: RADIO md 의 인용문(> …) + R 절
 *  - 기본 스토리 1개 + variant 유니언별 스토리
 * 이미 손으로 쓴 *.stories.tsx 가 있으면 건너뛴다(덮어쓰지 않음). 실행: pnpm gen:stories
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import ts from 'typescript';

const UI = join(process.cwd(), 'packages/ui/src'), RADIO = join(process.cwd(), 'docs/radio');

function propsOf(file: string, typeName: string) {
  const src = ts.createSourceFile(file, readFileSync(file, 'utf8'), ts.ScriptTarget.Latest, true);
  const out: { name: string; kind: 'enum' | 'boolean' | 'text' | 'number' | 'none'; options?: string[]; optional: boolean }[] = [];
  const visit = (n: ts.Node) => {
    if (ts.isTypeAliasDeclaration(n) && n.name.text === typeName) {
      const collect = (t: ts.TypeNode) => {
        if (ts.isTypeLiteralNode(t)) for (const m of t.members) if (ts.isPropertySignature(m) && m.type && ts.isIdentifier(m.name)) {
          const ty = m.type, txt = ty.getText();
          let kind: any = 'none', options: string[] | undefined;
          if (ts.isUnionTypeNode(ty) && ty.types.every(x => ts.isLiteralTypeNode(x) && ts.isStringLiteral(x.literal))) { kind = 'enum'; options = ty.types.map(x => (x as any).literal.text); }
          else if (txt === 'boolean') kind = 'boolean'; else if (txt === 'string') kind = 'text'; else if (txt === 'number') kind = 'number';
          out.push({ name: m.name.text, kind, options, optional: !!m.questionToken });
        }
        if (ts.isIntersectionTypeNode(t)) t.types.forEach(collect);
        if (ts.isParenthesizedTypeNode(t)) collect(t.type);
        // NativeProps<'div', Own> · PolymorphicProps<C, Own> 처럼 Own 을 마지막 타입 인자로 받는 래퍼는
        // 그 인자 안에 실제 props 가 있습니다. 이걸 따라가지 않으면 props 를 0개로 보고 조용히 건너뜁니다.
        if (ts.isTypeReferenceNode(t) && /^(NativeProps|PolymorphicProps)$/.test(t.typeName.getText()) && t.typeArguments?.length) {
          collect(t.typeArguments[t.typeArguments.length - 1]);
        }
      };
      collect(n.type);
    }
    ts.forEachChild(n, visit);
  };
  visit(src); return out;
}
function radio(name: string) {
  const p = join(RADIO, name + '.md'); if (!existsSync(p)) return '';
  const md = readFileSync(p, 'utf8'); const intro = (md.match(/^> (.+)$/m) || [])[1] ?? '';
  const R = (md.split(/^## R[^\n]*$/m)[1] || '').split(/^## /m)[0].trim();
  return [intro, '', '**Requirements**', R].join('\n').replace(/`/g, '\\`');
}
for (const dir of readdirSync(UI, { withFileTypes: true }).filter(d => d.isDirectory() && /^[A-Z]/.test(d.name))) {
  const name = dir.name, comp = join(UI, name, name + '.tsx'), story = join(UI, name, name + '.stories.tsx');
  if (!existsSync(comp) || existsSync(story)) continue;
  const props = propsOf(comp, name + 'OwnProps').concat(propsOf(comp, name + 'Props')).filter((p, i, a) => a.findIndex(x => x.name === p.name) === i);
  if (!props.length) continue;
  // args 없이 렌더되므로, 채울 수 없는 필수 props(배열·객체·ReactNode·함수)가 하나라도 있으면 건너뜁니다.
  // 예전엔 `Default: S = {}` 를 그대로 써서 Tabs(items) · Slider(value) 같은 컴포넌트가
  // "Cannot read properties of undefined (reading 'map')" 로 스토리북 a11y 러너를 깨뜨렸습니다.
  const unfillable = props.filter(p => !p.optional && p.kind === 'none').map(p => p.name);
  if (unfillable.length) { console.log('skip:', name, '— 필수 props 를 생성할 수 없음(손으로 스토리 작성):', unfillable.join(', ')); continue; }
  // 접근성 이름을 만드는 props 는 반드시 채웁니다 — 비워 두면 라벨 없는 입력이 되어 axe 가 critical 로 잡습니다.
  const SAMPLE: Record<string, string> = {
    label: '라벨', title: '제목', alt: '설명', name: '이름',
    placeholder: '입력하세요', helper: '도움말', hint: '설명',
  };
  const args = props
    // label · title 은 보통 ReactNode(kind 'none') 지만 문자열을 그대로 받습니다.
    .filter(p => SAMPLE[p.name] && (p.kind === 'text' || p.kind === 'none'))
    .map(p => `    ${p.name}: '${SAMPLE[p.name]}',`)
    .join('\n');
  const argTypes = props.map(p => p.kind === 'enum' ? `    ${p.name}: { control: 'inline-radio', options: ${JSON.stringify(p.options)} },` : p.kind === 'none' ? `    ${p.name}: { control: false },` : `    ${p.name}: { control: '${p.kind}' },`).join('\n');
  const variant = props.find(p => p.kind === 'enum' && /variant|tone|size|kind|layout/.test(p.name));
  const extra = variant ? variant.options!.map(o => `export const ${o[0].toUpperCase() + o.slice(1).replace(/-/g, '')}: S = { args: { ${variant.name}: '${o}' } };`).join('\n') : '';
  writeFileSync(story, `// generated by scripts/gen-stories.ts — 손으로 고치면 다음 생성 때 건너뜀
import type { Meta, StoryObj } from '@storybook/react';
import { ${name} } from './${name}';

const meta: Meta<typeof ${name}> = {
  title: 'Components/${name}',
  component: ${name},
  tags: ['autodocs'],${args ? `\n  args: {\n${args}\n  },` : ''}
  argTypes: {
${argTypes}
  },
  parameters: { docs: { description: { component: \`${radio(name)}\` } } },
};
export default meta;
type S = StoryObj<typeof ${name}>;
export const Default: S = {};
${extra}
`);
  console.log('stories:', name);
}
