import type { Meta, StoryObj } from '@storybook/react-vite';
import radio from '../../../../docs/radio/Tag.md?raw';
import { radioDescription } from '../storybook-radio';
import { Tag } from './Tag';
const meta: Meta<typeof Tag> = { title: 'Components/Tag', component: Tag, tags: ['autodocs'], args: { children: '진행중', variant: 'accent' }, argTypes: { variant: { control: 'inline-radio', options: ['accent', 'neutral', 'outline'] } }, parameters: { docs: { description: { component: radioDescription(radio) } } } };
export default meta;
type S = StoryObj<typeof Tag>;
export const Accent: S = {};
export const All: S = { render: () => <div style={{ display: 'flex', gap: 8 }}><Tag variant="accent">진행중</Tag><Tag variant="neutral">검토</Tag><Tag variant="outline">완료</Tag></div> };
export const AsLink: S = { render: () => <Tag as="a" href="/status" variant="outline">상태 보기</Tag> };
