// generated by scripts/gen-stories.ts — 손으로 고치면 다음 생성 때 건너뜀
import type { Meta, StoryObj } from '@storybook/react';
import { Avatar } from './Avatar';

const meta: Meta<typeof Avatar> = {
  title: 'Components/Avatar',
  component: Avatar,
  tags: ['autodocs'],
  args: {
    name: '이름',
  },
  argTypes: {
    name: { control: 'text' },
    src: { control: false },
    size: { control: false },
    shape: { control: 'inline-radio', options: ["square","circle"] },
    status: { control: 'inline-radio', options: ["online","busy"] },
  },
  parameters: { docs: { description: { component: `이니셜 폴백 아바타 + 그룹.

**Requirements**
- 4 크기, 사진은 grayscale, 상태점, Group 은 +N
- 이름 첫 글자(한글) / 이니셜 2자(영문)
- role=img aria-label=이름` } } },
};
export default meta;
type S = StoryObj<typeof Avatar>;
export const Default: S = {};

